### PR TITLE
Update docs for Laravel 5.4

### PR DESCRIPTION
**Pull request by bobbybouwmann**
Hi,

I did the following updates on the documentation:

- Updated docs for all packages that are already updated for 5.4
- Added quote for packages that are not updated yet

### CODE REVIEW

**Comment by mlantz** [comment]
The remote package is prepped for 5.4 :)

**Comment by bobbybouwmann** [comment]
Great

**Comment by bbashy** [comment]
When will the website start showing 5.4 as an option?

Had loads of people asking me if they can install it for 5.4

**Comment by bobbybouwmann** [comment]
@mlantz Is there a reason why this PR isn't merged yet?

**Comment by fonini** [comment]
Any news?

**Comment by mlantz** [comment]
Sorry about all this folks. Also, I dont have site publishing auth currently. I'm inquiring if I can start doing that. Sorry for all the delays.

**Comment by bobbybouwmann** [comment]
Wooeeh, thanks for merging this!

**Comment by bobbybouwmann** [comment]
@mlantz Do you have an estimated time until this will be published? This won't do any good for the package since Laravel 5.4 is out for a while now. Other html/form package start to become more popular because of this. For example: https://github.com/spatie/laravel-html

**Pull request merged**
