### PR TITLE
Clarify that array is 2nd param for Form::password

### PR DESCRIPTION
**Pull request by ghost**
Hi!

Had some confusion today about why Form::password wasn't working as we thought it would. Poked at the code and discovered that, like Form::file, Form::password only accepts two parameters: name and attributes. This is different from other text-like elements like Form::text or Form::email that accept value as the second param and attributes as the third. (This all makes sense, of course, but wanted to save someone else the time by explicitly putting this in the docs.)

Thanks for your work!

### CODE REVIEW

**Comment by adamgoose** [comment]
Since the docs display examples, instead of method signatures, can you replace that with something like `['class' => 'form-control']` or something like that?

Thanks,
Adam.

**Comment by ghost** [comment]
Oops, sure. I was just copying the syntax from Form::email and Form::file. ;-)

**Comment by ghost** [comment]
There you go. Used the attributes array from "Specifying Extra HTML Attributes" for consistency.
Thanks again!

**Comment by adamgoose** [comment]
Thanks! :D

**Pull request merged**
